services:
  mock-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lim_ai_mock_server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=${API_KEY}
    restart: unless-stopped
