api_key: ''
credentials:
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: c137f1b5-3aa7-451c-9ed7-e25b63e00991
  model: qwen
  name: Concept Map Qwen
  scope: concept_map
  type: llm_cloud
- access_token: null
  api_base: null
  api_key: null
  enabled: false
  id: 18bb19b9-c754-4776-992e-0eb17c0e0fb6
  model: gemma
  name: Translate Gemma
  scope: translation
  type: llm_ollama
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: 7688b3bc-2d6d-4b61-9be9-ebb24b45d362
  model: deepseek
  name: Translate DeepSeek
  scope: translation
  type: llm_cloud
disable_local_backup: false
remote_action_timeout_seconds: 30
remote_base_url: http://192.168.1.100:8000
silence_rms_threshold: 400
