api_key: ''
credentials:
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: 88be33cb-8e3c-44fe-9e14-5b3460b19773
  model: qwen
  name: Concept Map Qwen
  scope: concept_map
  type: llm_cloud
- access_token: null
  api_base: null
  api_key: null
  enabled: false
  id: 01ced9b2-3b92-4782-88e1-2f22e596d759
  model: gemma
  name: Translate Gemma
  scope: translation
  type: llm_ollama
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: b0983cb2-bf31-4458-9548-a23872396318
  model: deepseek
  name: Translate DeepSeek
  scope: translation
  type: llm_cloud
disable_local_backup: false
remote_action_timeout_seconds: 30
remote_base_url: http://192.168.1.100:8000
silence_rms_threshold: 400
