api_key: ''
credentials:
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: fcc0f122-0f41-4c33-a32f-e373533a88f9
  model: qwen
  name: Concept Map Qwen
  scope: concept_map
  type: llm_cloud
- access_token: null
  api_base: null
  api_key: null
  enabled: false
  id: d215bfdf-e8b4-4434-8b23-95f1ab087319
  model: gemma
  name: Translate Gemma
  scope: translation
  type: llm_ollama
- access_token: null
  api_base: null
  api_key: null
  enabled: true
  id: 8d650092-b480-49b3-ba65-37a99166956f
  model: deepseek
  name: Translate DeepSeek
  scope: translation
  type: llm_cloud
disable_local_backup: false
remote_action_timeout_seconds: 30
remote_base_url: http://192.168.1.100:8000
silence_rms_threshold: 400
