"""
Mermaid Validator and Sanitizer Service.

Design Note:
    This module provides strict server-side validation and sanitization for Mermaid.js
    syntax generated by LLM models. It cleans markdown fences, checks for valid starting
    keywords (graph, flowchart, mindmap), and parses regex checks to prevent XSS attacks
    (disallowing script tags, iframe, img tags, or javascript: schemes) before rendering.
"""

import logging
import re

logger = logging.getLogger("server_mermaid_validator")


class InvalidMermaidError(ValueError):
    """Exception raised when LLM-generated Mermaid code fails validation/sanitization."""
    pass


def validate_and_sanitize_mermaid(code: str) -> str:
    """
    Strips Markdown code blocks, validates keywords, and filters out XSS risks.

    Args:
        code: The raw input code generated by the LLM.

    Returns:
        The sanitized, clean Mermaid diagram code.

    Raises:
        InvalidMermaidError: with a clear validation error code/detail.
    """
    if not code:
        raise InvalidMermaidError("Il contenuto generato dal modello è vuoto.")

    cleaned = code.strip()

    # 1. Strip Markdown code fences if the model included them
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if len(lines) >= 2:
            if lines[0].strip().startswith("```"):
                lines = lines[1:]
            if lines[-1].strip().startswith("```"):
                lines = lines[:-1]
            cleaned = "\n".join(lines).strip()

    cleaned = cleaned.replace("```mermaid", "").replace("```", "").strip()

    if not cleaned:
        raise InvalidMermaidError("Il contenuto generato è vuoto dopo la rimozione dei code fences.")

    # 2. Check starting keyword (graph, flowchart, mindmap)
    first_non_empty_line = ""
    for line in cleaned.splitlines():
        line_strip = line.strip()
        if line_strip:
            first_non_empty_line = line_strip
            break

    first_line_lower = first_non_empty_line.lower()
    valid_keywords = ("graph", "flowchart", "mindmap")
    if not any(first_line_lower.startswith(kw) for kw in valid_keywords):
        logger.warning("Mermaid validation failed: Invalid starting keyword.")
        raise InvalidMermaidError(
            "Il diagramma Mermaid generato non inizia con una parola chiave valida "
            "(graph, flowchart, mindmap)."
        )

    # 3. Security: Check for XSS vectors
    xss_patterns = [
        r"<script\b[^>]*>",
        r"<img\b[^>]*>",
        r"<iframe\b[^>]*>",
        r"\bjavascript\s*:"
    ]
    for pattern in xss_patterns:
        if re.search(pattern, cleaned, re.IGNORECASE):
            logger.warning("Mermaid security check failed: Detected potential XSS vector.")
            raise InvalidMermaidError("Rilevato potenziale contenuto XSS non sicuro nell'output.")

    return cleaned
