"""
Quiz Validator Service.

Design Note:
    This module provides strict server-side validation and parsing for quizzes
    generated by LLM models. It cleans markdown fences, parses the output as JSON,
    and checks the structural schema: must be a list containing between 3 and 5 questions,
    each with a non-empty question string, at least 2 options, and a valid correct_index.
"""

import json
import logging

logger = logging.getLogger("server_quiz_validator")


class InvalidQuizError(ValueError):
    """Exception raised when LLM-generated Quiz fails validation."""
    pass


def validate_and_parse_quiz(content: str) -> list[dict]:
    """
    Strips markdown code blocks, parses JSON, and performs strict structural validation.

    Args:
        content: Raw output from the LLM.

    Returns:
        List of validated question dictionaries.

    Raises:
        InvalidQuizError: if validation fails.
    """
    if not content:
        raise InvalidQuizError("Il contenuto generato dal modello è vuoto.")

    cleaned = content.strip()

    # Strip markdown code blocks if the model included them
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if len(lines) >= 2:
            if lines[0].strip().startswith("```"):
                lines = lines[1:]
            if lines[-1].strip().startswith("```"):
                lines = lines[:-1]
            cleaned = "\n".join(lines).strip()

    cleaned = cleaned.replace("```json", "").replace("```", "").strip()

    if not cleaned:
        raise InvalidQuizError("Il contenuto generato è vuoto dopo la rimozione dei code fences.")

    # Parse JSON
    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        logger.warning("Quiz parsing failed: Invalid JSON format. Error: %s", e)
        raise InvalidQuizError(f"Formato JSON non valido: {e}")

    if not isinstance(data, list):
        logger.warning("Quiz validation failed: Root is not a list.")
        raise InvalidQuizError("L'output non è una lista JSON.")

    # Check question count (must be between 3 and 5 questions)
    if not (3 <= len(data) <= 5):
        logger.warning("Quiz validation failed: Question count %d is out of bounds [3, 5].", len(data))
        raise InvalidQuizError(f"Il numero di domande ({len(data)}) deve essere compreso tra 3 e 5.")

    # Validate each question item
    for idx, item in enumerate(data):
        if not isinstance(item, dict):
            raise InvalidQuizError(f"La domanda all'indice {idx} non è un oggetto dizionario.")

        # Question text validation
        question_text = item.get("question")
        if not question_text or not isinstance(question_text, str) or not question_text.strip():
            raise InvalidQuizError(f"La domanda all'indice {idx} ha un testo non valido o vuoto.")

        # Options validation
        options = item.get("options")
        if not isinstance(options, list):
            raise InvalidQuizError(f"La domanda all'indice {idx} non ha un'opzione di tipo lista.")

        if len(options) < 2:
            raise InvalidQuizError(
                f"La domanda all'indice {idx} deve avere almeno 2 opzioni (trovate {len(options)})."
            )

        # Check options items are strings or non-empty
        for opt_idx, opt in enumerate(options):
            if not isinstance(opt, str) or not opt.strip():
                raise InvalidQuizError(
                    f"L'opzione all'indice {opt_idx} della domanda {idx} non è una stringa valida."
                )

        # Correct index validation
        correct_index = item.get("correct_index")
        # Ensure it is an integer (and not a boolean, since bool is a subclass of int)
        if isinstance(correct_index, bool) or not isinstance(correct_index, int):
            raise InvalidQuizError(f"Il correct_index alla domanda {idx} deve essere un numero intero.")

        if not (0 <= correct_index < len(options)):
            raise InvalidQuizError(
                f"Il correct_index ({correct_index}) alla domanda {idx} è fuori dai limiti [0, {len(options)-1}]."
            )

    return data
